### ISSUE TITLE
CIS 194: Introduction to Haskell (Spring 2015)

### ISSUE THREAD

**Issue by afhole** [bitemyapp/learnhaskell#40]
I was curious to know if you have evaluated CIS 194: Introduction to Haskell (Spring 2015) and if so what is your opinion of it? Does it resolve the issues with the Fall 2014 course or is Spring 2013 still the best?

Many Thanks

**Comment by bitemyapp** [comment]
@afhole Spring 2015 is too early to judge. Did you look at the lectures? There's [barely anything there](https://www.seas.upenn.edu/~cis194/lectures.html).

Based on the way [Fall 2014](https://www.seas.upenn.edu/~cis194/fall14/) went, I doubt Spring 2015 will be usable for self-learners.

I am intentionally linking the oldest version because that's the only one usable for independent learners. I had a feeling cis194 would be reliably useful for non-UPenn students which is why I am focusing on writing [my book](http://haskellbook.com/).

Thanks for pinging, but yeah, probably not much to harvest here.

I wrote a [review of the resources for learning functional programming on my blog](http://bitemyapp.com/posts/2014-12-31-functional-education.html) - I explain what's wrong with the newer cis194 course there.

**Comment by 2016rshah** [comment]
Bump. I am not sure what was there in January but it seems that the lectures have been added. Are they any better/worse than those of 2013?

**Comment by bitemyapp** [comment]
@2016rshah The newest cis194 remains an intermediate class, not a suitable introduction to functional programming so the recommendation that people use Spring '13 holds.

**Comment by 2016rshah** [comment]
Great, just making sure :+1:
