### ISSUE TITLE
Haskell on docker and vagrant

### ISSUE THREAD

**Issue by pawelsawicz** [bitemyapp/learnhaskell#60]
We could add info about haskell on docker / vagrant into guide 

Example usage both of platforms for haskell :
[haskell on docker](https://github.com/freebroccolo/docker-haskell)
[haskell on vagrant](https://github.com/freebroccolo/vagrant-haskell)

I will try prepare PR for this.

**Comment by bitemyapp** [comment]
It's not clear that either are being maintained.

**Comment by davewalk** [comment]
There is a [standard Docker image](https://registry.hub.docker.com/_/haskell/) that can be trusted. I'm using the REPL now to mess around with Haskell for the first time.

@bitemyapp I can write some documentation on how to use if you think it makes sense (it would basically be the docs for that repo).

**Comment by bitemyapp** [comment]
@davewalk I'd really like to not give new users (learners) of Haskell the impression that these are things they need to do in order to learn Haskell. This guide is for people who haven't yet learnt Haskell, it's not for production users figuring out productionization. If we did include Docker instructions, I'd prefer it be in the second half of the guide after the essential educational resources and with a qualifier that explains you don't *have* to use these tools to learn and use Haskell on your own computer.

If that works for you, I think instructions would be helpful for people who don't know want to use for (Docker && Haskell).

**Comment by pawelsawicz** [comment]
@bitemyapp Yes totally agree. We could do separate section that won't indicate that it's required. I thought that it could be useful for experienced programmers in other languages, who knows about Docker and Vagrant.
