### ISSUE TITLE
Explain why I shouldn't install Haskell platform

### ISSUE THREAD

**Issue by rcknight** [bitemyapp/learnhaskell#78]
I'm sure there is a good reason, but nearly the first thing people read here is a rather unfriendly all-caps "DO NOT INSTALL HASKELL PLATFORM". If you are going to recommend people deviate from the instructions on haskell.org, I'd really like to be told why I should do so.

I arrived at this page having already installed Haskell Platform, so without hearing the context behind the statement i'm not really sure how I should proceed. I suspect i'm not the only one in that situation.

Could someone add an explanation about why the platform installer is bad?

**Comment by doppioslash** [comment]
In my experience: mainly because it doesn't work.
It pollutes your system with a not easily upgradeable version of ghc and cabal, which may be hard to eradicate when you want to get rid of it (and you will).
It's a few versions behind, so when you want to use libraries that require a newer ghc or cabal, you end up straight in cabal hell.
I don't know why they still tell people to use Haskell platform, but it never worked properly for me on mac. Might be ok for Windows, I never tried that.

A good summary: "It is a trap. The only good part is that it is a quick way to have Haskell on your system. But then it comes back at you." 
Taken from: https://www.reddit.com/r/haskell/comments/2w3php/venerable_haskell_platform_necessity_or_product/

Alternatives:
I use [halcyon](https://halcyon.sh/) but they say good things about [stackage](https://www.stackage.org/) and [nix](https://nixos.org/nix/)

**Comment by bitemyapp** [comment]
What @doppioslash said characterizes it well.

From that thread, my thoughts are summarized here: https://www.reddit.com/r/haskell/comments/2w3php/venerable_haskell_platform_necessity_or_product/conbiu5

It installs packages into the global package-db that don't need to be which causes breakages new people don't how to deal with when they eventually become out of date. The story for most people WRT upgrading between versions of the Platform has been, "blow away everything, reinstall" which is not great considering the pace the package ecosystem operates at.

The recommendations in this guide for how to install GHC/Cabal still hold, but I've also been enjoying [Stack](https://github.com/commercialhaskell/stack/) for my day to day work. I'm undecided yet as to how to handle explaining Stack to new people so I've not changed the recommendations for now.
